import type { CaptionConfig, CaptionStyle } from "../types/captions";

export type PresetName = CaptionStyle;

export interface PresetInfo {
  id: PresetName;
  label: string;
  description: string;
  colors: string[];
  config: CaptionConfig;
}

export const SIMPLE_PRESET: CaptionConfig = {
  fontSize: 54,
  textColor: "#FFFFFF",
  fontFamily: "inter",
  backgroundColor: "transparent",
  backgroundColors: [],
  showBackground: false,
  showDithering: false,
  strokeColor: "#000000",
  strokeWidth: 0,
  shadowColor: "#000000",
  shadowBlur: 4,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 15,
  leftRightPadding: 7.5,
  animationStyle: "fade",
  animationIntensity: 100,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FFD700",
  highlightScale: 1.05,
  uppercase: false,
  letterSpacing: 0,
  lineHeight: 1.4,
  fontWeight: 500,
  wordSpacing: 6,
  pageCombineMs: 700,
};

export const COMIC_PRESET: CaptionConfig = {
  fontSize: 62,
  textColor: "#FFFFFF",
  fontFamily: "comic",
  backgroundColor: "#FFD700",
  backgroundColors: ["#FFD700", "#3B82F6", "#EF4444", "#22C55E"],
  showBackground: true,
  showDithering: true,
  strokeColor: "#000000",
  strokeWidth: 4,
  shadowColor: "#000000",
  shadowBlur: 0,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 15,
  leftRightPadding: 7.5,
  animationStyle: "pop",
  animationIntensity: 100,
  rotation: true,
  rotationMax: 2,
  highlightColor: "#FF6B35",
  highlightScale: 1.3,
  uppercase: true,
  letterSpacing: 1,
  lineHeight: 1.3,
  fontWeight: 400,
  wordSpacing: 10,
  pageCombineMs: 700,
};

export const CLEAN_PRESET: CaptionConfig = {
  fontSize: 50,
  textColor: "#FFFFFF",
  fontFamily: "plusJakartaSans",
  backgroundColor: "transparent",
  backgroundColors: [],
  showBackground: false,
  showDithering: false,
  strokeColor: "#000000",
  strokeWidth: 0,
  shadowColor: "#000000",
  shadowBlur: 6,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 14,
  leftRightPadding: 8,
  animationStyle: "fade",
  animationIntensity: 70,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#818CF8",
  highlightScale: 1.05,
  uppercase: false,
  letterSpacing: 0.2,
  lineHeight: 1.45,
  fontWeight: 400,
  wordSpacing: 6,
  pageCombineMs: 700,
};

export const NEON_PRESET: CaptionConfig = {
  fontSize: 58,
  textColor: "#00FFAA",
  fontFamily: "inter",
  backgroundColor: "#000000",
  backgroundColors: ["#0D0D0D"],
  showBackground: true,
  showDithering: false,
  strokeColor: "#00FFAA",
  strokeWidth: 2,
  shadowColor: "#00FFAA",
  shadowBlur: 12,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 15,
  leftRightPadding: 7.5,
  animationStyle: "fade",
  animationIntensity: 80,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FF00FF",
  highlightScale: 1.15,
  uppercase: false,
  letterSpacing: 1,
  lineHeight: 1.4,
  fontWeight: 500,
  wordSpacing: 8,
  pageCombineMs: 700,
};

export const MINIMAL_PRESET: CaptionConfig = {
  fontSize: 48,
  textColor: "#FFFFFF",
  fontFamily: "inter",
  backgroundColor: "#00000080",
  backgroundColors: ["#00000080"],
  showBackground: true,
  showDithering: false,
  strokeColor: "transparent",
  strokeWidth: 0,
  shadowColor: "#000000",
  shadowBlur: 2,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 12,
  leftRightPadding: 10,
  animationStyle: "fade",
  animationIntensity: 60,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#60A5FA",
  highlightScale: 1.05,
  uppercase: false,
  letterSpacing: 0.5,
  lineHeight: 1.5,
  fontWeight: 400,
  wordSpacing: 6,
  pageCombineMs: 600,
};

export const KARAOKE_PRESET: CaptionConfig = {
  fontSize: 56,
  textColor: "#FFFFFF",
  fontFamily: "poppins",
  backgroundColor: "#7C3AED",
  backgroundColors: ["#7C3AED", "#EC4899", "#F97316"],
  showBackground: true,
  showDithering: false,
  strokeColor: "#4C1D95",
  strokeWidth: 2,
  shadowColor: "#7C3AED",
  shadowBlur: 8,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 12,
  leftRightPadding: 8,
  animationStyle: "swipe",
  animationIntensity: 70,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FDE047",
  highlightScale: 1.25,
  uppercase: false,
  letterSpacing: 0.5,
  lineHeight: 1.4,
  fontWeight: 500,
  wordSpacing: 7,
  pageCombineMs: 800,
};

export const RETRO_PRESET: CaptionConfig = {
  fontSize: 52,
  textColor: "#FDE68A",
  fontFamily: "oswald",
  backgroundColor: "#1E1B4B",
  backgroundColors: ["#1E1B4B", "#312E81"],
  showBackground: true,
  showDithering: true,
  strokeColor: "#FDE68A",
  strokeWidth: 3,
  shadowColor: "#000000",
  shadowBlur: 0,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 14,
  leftRightPadding: 7,
  animationStyle: "shake",
  animationIntensity: 50,
  rotation: true,
  rotationMax: 1.5,
  highlightColor: "#F97316",
  highlightScale: 1.2,
  uppercase: true,
  letterSpacing: 2,
  lineHeight: 1.3,
  fontWeight: 500,
  wordSpacing: 10,
  pageCombineMs: 700,
};

export const TYPEWRITER_PRESET: CaptionConfig = {
  fontSize: 44,
  textColor: "#E2E8F0",
  fontFamily: "roboto",
  backgroundColor: "#0F172A",
  backgroundColors: ["#0F172AE0"],
  showBackground: true,
  showDithering: false,
  strokeColor: "transparent",
  strokeWidth: 0,
  shadowColor: "#000000",
  shadowBlur: 3,
  verticalAlign: "bottom",
  horizontalAlign: "left",
  bottomOffset: 10,
  leftRightPadding: 6,
  animationStyle: "fade",
  animationIntensity: 40,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#38BDF8",
  highlightScale: 1.0,
  uppercase: false,
  letterSpacing: 0.8,
  lineHeight: 1.6,
  fontWeight: 400,
  wordSpacing: 5,
  pageCombineMs: 500,
};

export const GRADIENT_PRESET: CaptionConfig = {
  fontSize: 60,
  textColor: "#FFFFFF",
  fontFamily: "montserrat",
  backgroundColor: "#BE185D",
  backgroundColors: ["#BE185D", "#7C3AED", "#2563EB", "#0891B2"],
  showBackground: true,
  showDithering: false,
  strokeColor: "#FFFFFF",
  strokeWidth: 1,
  shadowColor: "#BE185D",
  shadowBlur: 10,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 15,
  leftRightPadding: 8,
  animationStyle: "pop",
  animationIntensity: 80,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FDE047",
  highlightScale: 1.2,
  uppercase: false,
  letterSpacing: 0.5,
  lineHeight: 1.35,
  fontWeight: 600,
  wordSpacing: 8,
  pageCombineMs: 700,
};

export const OUTLINE_PRESET: CaptionConfig = {
  fontSize: 58,
  textColor: "#FFFFFF",
  fontFamily: "raleway",
  backgroundColor: "transparent",
  backgroundColors: [],
  showBackground: false,
  showDithering: false,
  strokeColor: "#FFFFFF",
  strokeWidth: 5,
  shadowColor: "#000000",
  shadowBlur: 0,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 15,
  leftRightPadding: 7,
  animationStyle: "slam",
  animationIntensity: 90,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#F43F5E",
  highlightScale: 1.15,
  uppercase: true,
  letterSpacing: 2,
  lineHeight: 1.3,
  fontWeight: 700,
  wordSpacing: 8,
  pageCombineMs: 700,
};

export const BROADCAST_PRESET: CaptionConfig = {
  fontSize: 46,
  textColor: "#FFFFFF",
  fontFamily: "lexend",
  backgroundColor: "#000000CC",
  backgroundColors: ["#000000CC"],
  showBackground: true,
  showDithering: false,
  strokeColor: "transparent",
  strokeWidth: 0,
  shadowColor: "#000000",
  shadowBlur: 2,
  verticalAlign: "bottom",
  horizontalAlign: "left",
  bottomOffset: 8,
  leftRightPadding: 5,
  animationStyle: "fade",
  animationIntensity: 50,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FBBF24",
  highlightScale: 1.0,
  uppercase: false,
  letterSpacing: 0.3,
  lineHeight: 1.5,
  fontWeight: 400,
  wordSpacing: 5,
  pageCombineMs: 600,
};

export const HANDWRITTEN_PRESET: CaptionConfig = {
  fontSize: 58,
  textColor: "#FEFCE8",
  fontFamily: "caveat",
  backgroundColor: "transparent",
  backgroundColors: [],
  showBackground: false,
  showDithering: false,
  strokeColor: "#000000",
  strokeWidth: 0,
  shadowColor: "#78350F",
  shadowBlur: 6,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 14,
  leftRightPadding: 7,
  animationStyle: "fade",
  animationIntensity: 80,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#FB923C",
  highlightScale: 1.1,
  uppercase: false,
  letterSpacing: 0.5,
  lineHeight: 1.3,
  fontWeight: 700,
  wordSpacing: 6,
  pageCombineMs: 700,
};

export const SOFT_PRESET: CaptionConfig = {
  fontSize: 50,
  textColor: "#1E293B",
  fontFamily: "quicksand",
  backgroundColor: "#FFFFFFD9",
  backgroundColors: ["#FFFFFFD9"],
  showBackground: true,
  showDithering: false,
  strokeColor: "transparent",
  strokeWidth: 0,
  shadowColor: "#94A3B8",
  shadowBlur: 4,
  verticalAlign: "bottom",
  horizontalAlign: "center",
  bottomOffset: 12,
  leftRightPadding: 8,
  animationStyle: "fade",
  animationIntensity: 60,
  rotation: false,
  rotationMax: 0,
  highlightColor: "#7C3AED",
  highlightScale: 1.05,
  uppercase: false,
  letterSpacing: 0.3,
  lineHeight: 1.45,
  fontWeight: 500,
  wordSpacing: 6,
  pageCombineMs: 700,
};

export const ALL_PRESETS: PresetInfo[] = [
  {
    id: "simple",
    label: "Simple",
    description: "Clean white with shadow",
    colors: ["#FFFFFF", "#E2E8F0"],
    config: SIMPLE_PRESET,
  },
  {
    id: "clean",
    label: "Clean",
    description: "Modern, minimal, elegant",
    colors: ["#FFFFFF", "#818CF8"],
    config: CLEAN_PRESET,
  },
  {
    id: "minimal",
    label: "Minimal",
    description: "Subtle dark pill",
    colors: ["#FFFFFF", "#64748B"],
    config: MINIMAL_PRESET,
  },
  {
    id: "soft",
    label: "Soft",
    description: "Light, rounded, gentle",
    colors: ["#FFFFFF", "#7C3AED"],
    config: SOFT_PRESET,
  },
  {
    id: "broadcast",
    label: "Broadcast",
    description: "News-style, left-aligned",
    colors: ["#FFFFFF", "#0F172A"],
    config: BROADCAST_PRESET,
  },
  {
    id: "typewriter",
    label: "Typewriter",
    description: "Dark pill, left-aligned",
    colors: ["#E2E8F0", "#0F172A"],
    config: TYPEWRITER_PRESET,
  },
  {
    id: "handwritten",
    label: "Handwritten",
    description: "Casual, warm, personal",
    colors: ["#FEFCE8", "#FB923C"],
    config: HANDWRITTEN_PRESET,
  },
  {
    id: "karaoke",
    label: "Karaoke",
    description: "Purple glow, smooth swipe",
    colors: ["#7C3AED", "#EC4899", "#F97316"],
    config: KARAOKE_PRESET,
  },
  {
    id: "neon",
    label: "Neon",
    description: "Glowing text, dark bg",
    colors: ["#00FFAA", "#FF00FF"],
    config: NEON_PRESET,
  },
  {
    id: "gradient",
    label: "Gradient",
    description: "Colorful cycling backgrounds",
    colors: ["#BE185D", "#7C3AED", "#2563EB", "#0891B2"],
    config: GRADIENT_PRESET,
  },
  {
    id: "comic",
    label: "Comic",
    description: "Colorful, animated, fun",
    colors: ["#FFD700", "#3B82F6", "#EF4444", "#22C55E"],
    config: COMIC_PRESET,
  },
  {
    id: "outline",
    label: "Outline",
    description: "Heavy stroke, no background",
    colors: ["#FFFFFF", "#F43F5E"],
    config: OUTLINE_PRESET,
  },
  {
    id: "retro",
    label: "Retro",
    description: "Vintage, dithered, warm",
    colors: ["#FDE68A", "#1E1B4B"],
    config: RETRO_PRESET,
  },
];

export const PAGE_GROUPING_PRESETS = [
  { id: "word-by-word", label: "Word by word", ms: 200, description: "Each word is its own page" },
  { id: "short-phrases", label: "Short phrases", ms: 400, description: "2-3 words per page" },
  { id: "natural", label: "Natural", ms: 700, description: "Follows speech rhythm" },
  { id: "sentences", label: "Sentences", ms: 1200, description: "Longer caption groups" },
  { id: "paragraphs", label: "Paragraphs", ms: 2000, description: "Maximum grouping" },
] as const;

export function getPreset(name: string): CaptionConfig {
  const found = ALL_PRESETS.find((p) => p.id === name);
  return { ...(found?.config ?? SIMPLE_PRESET) };
}
